# cloudbuild.yaml for Node.js Backend API (WITH migrations + seeding)

steps:
  # 1. Build the all-purpose application image.
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Backend Image"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cmo-backend-api:$COMMIT_SHA", "."]

  # 2. Push the application image.
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Backend Image"
    args: ["push", "gcr.io/$PROJECT_ID/cmo-backend-api:$COMMIT_SHA"]

  # 3. Deploy the migration + seed Job definition.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Migration Job"
    entrypoint: "bash"
    secretEnv:
      - DB_INSTANCE_NAME
      - DATABASE_URL_SECRET
      - PAGESPEED_API_KEY_SECRET
      - GOOGLE_CLIENT_ID_SECRET
      - GOOGLE_CLIENT_SECRET_SECRET
      - GOOGLE_CALLBACK_URL_SECRET
      - SESSION_SECRET_SECRET
      - YOUTUBE_API_KEY_SECRET
      - OPENAI_API_KEY_SECRET
      - NEXT_PUBLIC_BASE_URL_SECRET
    args:
      - "-c"
      - |
        gcloud run jobs deploy cmo-db-migration-job \
          --image=gcr.io/$PROJECT_ID/cmo-backend-api:$COMMIT_SHA \
          --region=us-central1 \
          --set-cloudsql-instances=$$DB_INSTANCE_NAME \
          --set-secrets=DATABASE_URL=DATABASE_URL_SECRET:latest \
          --set-secrets=PAGESPEED_API_KEY=pagespeed-api-key:latest \
          --set-secrets=GOOGLE_CLIENT_ID=backend-google-client-id:latest \
          --set-secrets=GOOGLE_CLIENT_SECRET=backend-google-client-secret:latest \
          --set-secrets=GOOGLE_CALLBACK_URL=google-callback-url:latest \
          --set-secrets=SESSION_SECRET=session-secret:latest \
          --set-secrets=YOUTUBE_API_KEY=youtube-api-key:latest \
          --set-secrets=OPENAI_API_KEY=openai-api-key:latest \
          --set-secrets=NEXT_PUBLIC_BASE_URL=next-public-base-url:latest \
          --set-env-vars=TASK=migrate

  # 4. Execute the migration + seed Job and wait for it to complete.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Execute Migration Job"
    entrypoint: "gcloud"
    args: ["run", "jobs", "execute", "cmo-db-migration-job", "--region=us-central1", "--wait"]

  # 5. Deploy the main backend service if the migration job was successful.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Backend Service"
    entrypoint: "bash"
    secretEnv:
      - DB_INSTANCE_NAME
      - DATABASE_URL_SECRET
      - PAGESPEED_API_KEY_SECRET
      - GOOGLE_CLIENT_ID_SECRET
      - GOOGLE_CLIENT_SECRET_SECRET
      - GOOGLE_CALLBACK_URL_SECRET
      - SESSION_SECRET_SECRET
      - YOUTUBE_API_KEY_SECRET
      - OPENAI_API_KEY_SECRET
      - NEXT_PUBLIC_BASE_URL_SECRET
    args:
      - "-c"
      - |
        gcloud run deploy cmo-backend-api \
          --image=gcr.io/$PROJECT_ID/cmo-backend-api:$COMMIT_SHA \
          --region=us-central1 \
          --platform=managed \
          --add-cloudsql-instances=$$DB_INSTANCE_NAME \
          --set-secrets=DATABASE_URL=DATABASE_URL_SECRET:latest \
          --set-secrets=PAGESPEED_API_KEY=pagespeed-api-key:latest \
          --set-secrets=GOOGLE_CLIENT_ID=backend-google-client-id:latest \
          --set-secrets=GOOGLE_CLIENT_SECRET=backend-google-client-secret:latest \
          --set-secrets=GOOGLE_CALLBACK_URL=google-callback-url:latest \
          --set-secrets=SESSION_SECRET=session-secret:latest \
          --set-secrets=YOUTUBE_API_KEY=youtube-api-key:latest \
          --set-secrets=OPENAI_API_KEY=openai-api-key:latest \
          --set-secrets=NEXT_PUBLIC_BASE_URL=next-public-base-url:latest \
          --no-allow-unauthenticated

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-instance-name/versions/latest
      env: "DB_INSTANCE_NAME"
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL_SECRET/versions/latest
      env: "DATABASE_URL_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/pagespeed-api-key/versions/latest
      env: "PAGESPEED_API_KEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/backend-google-client-id/versions/latest
      env: "GOOGLE_CLIENT_ID_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/backend-google-client-secret/versions/latest
      env: "GOOGLE_CLIENT_SECRET_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/google-callback-url/versions/latest
      env: "GOOGLE_CALLBACK_URL_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/session-secret/versions/latest
      env: "SESSION_SECRET_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/youtube-api-key/versions/latest
      env: "YOUTUBE_API_KEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/openai-api-key/versions/latest
      env: "OPENAI_API_KEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/next-public-base-url/versions/latest
      env: "NEXT_PUBLIC_BASE_URL_SECRET"

options:
  logging: CLOUD_LOGGING_ONLY
